### ISSUE TITLE
我怎么运行.py文件呢而不执行单个语句获得输出呢

### ISSUE THREAD

**Issue by tghjnjvg** [pcy190/AndroidPython#1]
我怎么运行.py文件呢而不执行单个语句获得输出呢还有怎么支持第三方模块呢 比如.so和.requests

**Comment by pcy190** [comment]
`_DoFile`方法可以运行文件。
可以将第三方模块源码打包zip，而后添加到python搜索路径，例如
```
StarObjectClass python = service._ImportRawContext("python", "", false, "");
python._Call("import", "sys");
StarObjectClass pythonSys = python._GetObject("sys");
StarObjectClass pythonPath = (StarObjectClass) pythonSys._Get("path");
pythonPath._Call("insert", 0, APPFILEPATH +"MODULES.zip");
```
可以参考
https://github.com/joaoventura/pybridge/blob/master/app/src/main/java/com/jventura/pybridge/AssetExtractor.java

**Comment by tghjnjvg** [comment]
会不会有bug我去试试

**Comment by tghjnjvg** [comment]
app打开后闪退

**Comment by tghjnjvg** [comment]
03-15 16:33:10.961 4410-4499/? E/HiApp.InstalledAppDataMgr: main{1} <<< ERROR >>> removeInstalledApp, installedAppList == null
03-15 16:33:11.115 2527-2527/? E/HideAppsPagedView: syncPages mCurrentPage = 0
03-15 16:33:11.119 2527-2527/? E/HideAppsPagedView: syncAppsPageItems page = 0 mNumAppsPages = 1 mCurrentPage = 0
03-15 16:33:11.119 2527-2527/? E/HideAppsPagedView: createAddIcon count = 0
03-15 16:33:11.247 2539-2539/? E/HwSystemManager: AppCleanUpService:msg is 1
03-15 16:33:11.312 6190-6202/? E/linker: readlink('/proc/self/fd/24') failed: Permission denied [fd=24]
03-15 16:33:11.313 6190-6202/? E/linker: warning: unable to get realpath for the library "/system/lib64/hw/gralloc.hi6250.so". Will use given name.
03-15 16:33:11.452 4410-4499/? E/HiApp.InstalledAppDataMgr: main{1} <<< ERROR >>> the installed app list is not initial yet. it’s useless to update!
03-15 16:33:11.521 299-319/? E/PF_GP: [isValidCommand:94] [CPU_B] : invalid cmd, min=2112000, avlMin=1402000, avlMax=2016000
03-15 16:33:11.521 299-319/? E/PF_PR: [handleCommand:123] [CPU_B] : invalid cmd, cmdType=1, mFromEvent=5, mValues.size()=2
03-15 16:33:11.523 299-319/? E/PF_GP: [isValidCommand:94] [CPU_B] : invalid cmd, min=2112000, avlMin=1402000, avlMax=2016000
03-15 16:33:11.523 299-319/? E/PF_PR: [handleCommand:123] [CPU_B] : invalid cmd, cmdType=1, mFromEvent=4, mValues.size()=2
03-15 16:33:11.573 6254-6260/? E/art: Failed sending reply to debugger: Broken pipe
03-15 16:33:11.594 2539-2539/? E/HwSystemManager: AppCleanUpService:msg is 0
03-15 16:33:11.594 5196-5318/? E/HwSystemManager: SpaceCleanReceiver:doPkgAdd pi is not valid permission
03-15 16:33:12.366 1011-14255/? E/ReportTools: This is not beta user build
03-15 16:33:12.381 19598-6220/? E/ChromeSync: [Sync,SyncIntentOperation] Error handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.example.androidpython flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
03-15 16:33:12.471 1011-1277/? E/InputDispatcher: channel '8cd42c8 com.example.androidpython/com.example.androidpython.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-15 16:33:12.474 1011-1973/? E/HsmCoreServiceImpl: onTransact in code is: 102
03-15 16:33:12.493 3336-3448/? E/FileUtils: srcFile is not a file
03-15 16:33:12.493 3336-3448/? E/LogDatabase: Could not move to uploading path.
